[package]
name = "rgwsm_git"
version = "0.1.0"
authors = ["Peter Williams <pwil3058@gmail.com>"]
edition = "2018"

[dependencies]
gio = "0.4.0"
glib = "0.5.0"
gtk = "0.4.0"

pw_gix = { path = "../pw_gix" }
pw_pathux = { path = "../pw_pathux" }
